import {Chord} from "../interfaces/chord";

export const CHORD_CHAIN = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "Bb", "H"];

export const POSTFIX_CHAIN =['7', 'm', 'm7', 'maj7', 'sus4', '6', 'm6'];
// @ts-ignore
export const CHORDS: Chord[] = [
  // C
  {position: 0, spaces: 0},
  {position: 0, spaces: 0, postfix: 'm'},
  {position: 0, spaces: 0, postfix: 'maj7'},
  {position: 0, spaces: 0, postfix: 'sus4'},
  {position: 0, spaces: 0, postfix: '6'},
  {position: 0, spaces: 0, postfix: 'm6'},
  {position: 0, spaces: 0, postfix: '7'},
  {position: 0, spaces: 0, postfix: 'm7'},
  // C#
  {position: 1, spaces: 0},
  {position: 1, spaces: 0, postfix: 'm'},
  {position: 1, spaces: 0, postfix: 'maj7'},
  {position: 1, spaces: 0, postfix: 'sus4'},
  {position: 1, spaces: 0, postfix: '6'},
  {position: 1, spaces: 0, postfix: 'm6'},
  {position: 1, spaces: 0, postfix: '7'},
  {position: 1, spaces: 0, postfix: 'm7'},
  // D
  {position: 2, spaces: 0},
  {position: 2, spaces: 0, postfix: 'm'},
  {position: 2, spaces: 0, postfix: 'maj7'},
  {position: 2, spaces: 0, postfix: 'sus4'},
  {position: 2, spaces: 0, postfix: '6'},
  {position: 2, spaces: 0, postfix: 'm6'},
  {position: 2, spaces: 0, postfix: '7'},
  {position: 2, spaces: 0, postfix: 'm7'},
  // D#
  {position: 3, spaces: 0},
  {position: 3, spaces: 0, postfix: 'm'},
  {position: 3, spaces: 0, postfix: 'maj7'},
  {position: 3, spaces: 0, postfix: 'sus4'},
  {position: 3, spaces: 0, postfix: '6'},
  {position: 3, spaces: 0, postfix: 'm6'},
  {position: 3, spaces: 0, postfix: '7'},
  {position: 3, spaces: 0, postfix: 'm7'},
  // E
  {position: 4, spaces: 0},
  {position: 4, spaces: 0, postfix: 'm'},
  {position: 4, spaces: 0, postfix: 'maj7'},
  {position: 4, spaces: 0, postfix: 'sus4'},
  {position: 4, spaces: 0, postfix: '6'},
  {position: 4, spaces: 0, postfix: 'm6'},
  {position: 4, spaces: 0, postfix: '7'},
  {position: 4, spaces: 0, postfix: 'm7'},
  // F
  {position: 5, spaces: 0},
  {position: 5, spaces: 0, postfix: 'm'},
  {position: 5, spaces: 0, postfix: 'maj7'},
  {position: 5, spaces: 0, postfix: 'sus4'},
  {position: 5, spaces: 0, postfix: '6'},
  {position: 5, spaces: 0, postfix: 'm6'},
  {position: 5, spaces: 0, postfix: '7'},
  {position: 5, spaces: 0, postfix: 'm7'},
  // F#
  {position: 6, spaces: 0},
  {position: 6, spaces: 0, postfix: 'm'},
  {position: 6, spaces: 0, postfix: 'maj7'},
  {position: 6, spaces: 0, postfix: 'sus4'},
  {position: 6, spaces: 0, postfix: '6'},
  {position: 6, spaces: 0, postfix: 'm6'},
  {position: 6, spaces: 0, postfix: '7'},
  {position: 6, spaces: 0, postfix: 'm7'},
  // G
  {position: 7, spaces: 0},
  {position: 7, spaces: 0, postfix: 'm'},
  {position: 7, spaces: 0, postfix: 'maj7'},
  {position: 7, spaces: 0, postfix: 'sus4'},
  {position: 7, spaces: 0, postfix: '6'},
  {position: 7, spaces: 0, postfix: 'm6'},
  {position: 7, spaces: 0, postfix: '7'},
  {position: 7, spaces: 0, postfix: 'm7'},
  // G#
  {position: 8, spaces: 0},
  {position: 8, spaces: 0, postfix: 'm'},
  {position: 8, spaces: 0, postfix: 'maj7'},
  {position: 8, spaces: 0, postfix: 'sus4'},
  {position: 8, spaces: 0, postfix: '6'},
  {position: 8, spaces: 0, postfix: 'm6'},
  {position: 8, spaces: 0, postfix: '7'},
  {position: 8, spaces: 0, postfix: 'm7'},
  // A
  {position: 9, spaces: 0},
  {position: 9, spaces: 0, postfix: 'm'},
  {position: 9, spaces: 0, postfix: 'maj7'},
  {position: 9, spaces: 0, postfix: 'sus4'},
  {position: 9, spaces: 0, postfix: '6'},
  {position: 9, spaces: 0, postfix: 'm6'},
  {position: 9, spaces: 0, postfix: '7'},
  {position: 9, spaces: 0, postfix: 'm7'},
  // A#/Bb
  {position: 10, spaces: 0},
  {position: 10, spaces: 0, postfix: 'm'},
  {position: 10, spaces: 0, postfix: 'maj7'},
  {position: 10, spaces: 0, postfix: 'sus4'},
  {position: 10, spaces: 0, postfix: '6'},
  {position: 10, spaces: 0, postfix: 'm6'},
  {position: 10, spaces: 0, postfix: '7'},
  {position: 10, spaces: 0, postfix: 'm7'},
  // H
  {position: 11, spaces: 0},
  {position: 11, spaces: 0, postfix: 'm'},
  {position: 11, spaces: 0, postfix: 'maj7'},
  {position: 11, spaces: 0, postfix: 'sus4'},
  {position: 11, spaces: 0, postfix: '6'},
  {position: 11, spaces: 0, postfix: 'm6'},
  {position: 11, spaces: 0, postfix: '7'},
  {position: 11, spaces: 0, postfix: 'm7'},
]
